### ISSUE TITLE
gradle error

### ISSUE THREAD

**Issue by tonbash** [salRoid/Filmy#112]
when i try to import the project into android studio i get this error 
Error:Cause: secrets.properties (The system cannot find the file specified)

i already have tmdb, fabric, YouTube APIs 
![error](https://user-images.githubusercontent.com/20012690/27749436-49abdc9c-5ddc-11e7-9bec-ae90cbc6d668.PNG)

**Comment by salRoid** [comment]
You need to create a secret.properties in the project structure and insert your tmdb key and omdb key.
![screenshot 475](https://user-images.githubusercontent.com/10450754/27758507-e723ed6a-5e32-11e7-9a7e-44820a32188c.png)

**Comment by tonbash** [comment]
thanks its work
