### ISSUE TITLE
Fragment Not Closed

### ISSUE THREAD

**Issue by webianks** [salRoid/Filmy#114]
On Pressing cross button in character details fragment doesn't close fragment.

**Comment by salRoid** [comment]
Damn It

**Comment by webianks** [comment]
Things I do for *

**Comment by webianks** [comment]
Push the code then close this issue.

**Comment by salRoid** [comment]
Okay

**Comment by salRoid** [comment]
I guess I already pushed it !!

**Comment by salRoid** [comment]
https://github.com/jenkoian/hacktoberfest-checker

**Comment by salRoid** [comment]
yeh sahi kar diya tha !!

**Comment by salRoid** [comment]
Check It and Remove

**Comment by webianks** [comment]
Okay
