### ISSUE TITLE
Error:Cause: secrets.properties (No such file or directory)

### ISSUE THREAD

**Issue by dungnguyendotme** [salRoid/Filmy#116]
Please help me.
This occurs when I open project in Android Studio.
Thanks so much

**Comment by webianks** [comment]
You need to create a secret.properties in the project structure and insert your tmdb key and omdb key.
![27758507-e723ed6a-5e32-11e7-9a7e-44820a32188c](https://user-images.githubusercontent.com/8144959/28702514-190ca3f0-737b-11e7-97c2-0695a9bf8fc1.png)

**Comment by webianks** [comment]
Sorry for not mentioning in the readme. Will update that soon.

**Comment by dungnguyendotme** [comment]
Yes. I changed some code and I ran well last night. Best film info app ever. Thank you guy so much. And you must update Readme file more details.

**Comment by webianks** [comment]
Yeah, we will. Thanks.
