### ISSUE TITLE
Content AutoScrolled

### ISSUE THREAD

**Issue by webianks** [salRoid/Filmy#117]
Opening detailed activity moves focus to centre instead of top of the activity.

**Comment by XOptimistixX** [comment]
I can help fix this.

**Comment by webianks** [comment]
Go ahead.

**Comment by XOptimistixX** [comment]
Hmm for me the MovieDetails activity and CharacterDetailsActivity already have their focus at the top of the activity.

**Comment by XOptimistixX** [comment]
Any steps to reproduce the bug?

**Comment by salRoid** [comment]
@webianks not getting you  ?

**Comment by webianks** [comment]
Okay. I will check the updated code then close this issue.
