### ISSUE TITLE
In theaters and Upcoming Same Movies

### ISSUE THREAD

**Issue by salRoid** [salRoid/Filmy#122]
When a movie is in theaters  we can remove all of the same in upcoming as they are already released.
we have to write a query so that those with same movie id's don't get displayed.

**Comment by webianks** [comment]
Woo !! So much logic [sarcasm]. Do it then.

**Comment by salRoid** [comment]
Already Assigned it to myself bro

**Comment by salRoid** [comment]
You can't do that because ContentResolver has only one query method:
    query(Uri uri, String[] projection, String selection, 
String[] selectionArgs, String sortOrder)
there's no parameter for tables or FROM clauses.

**Comment by salRoid** [comment]
There might be some hack ..
