### ISSUE TITLE
Github Error View Library

### ISSUE THREAD

**Issue by salRoid** [salRoid/Filmy#126]
Update Error View Library to the latest version.

implementation 'tr.xip.errorview:library:4.0.0'

**Comment by webianks** [comment]
@salRoid is this fixed?

**Comment by webianks** [comment]
Okay so v4.0.0 uses Kotlin and there is a problem with passing a lambda in the retry method. Will upgrade when we move Filmy to Kotlin.

**Comment by salRoid** [comment]
Okay !

Regards
Sajal Gupta
www.salroid.me
