### ISSUE TITLE
ERROR: secrets.properties

### ISSUE THREAD

**Issue by Abdel-ilah** [salRoid/Filmy#127]
ERROR: secrets.properties (The system cannot find the file specified)
Open File

**Comment by ashishdeveloper1** [comment]
Same ERROR: secrets.properties (The system cannot find the file specified)
Open File

**Comment by samatzhusup** [comment]
SOLVED !!!!!!!!!!    https://github.com/salRoid/Filmy/issues/116 !!!!!!!!!!!
