### ISSUE TITLE
Details Dissappear

### ISSUE THREAD

**Issue by salRoid** [salRoid/Filmy#24]
Hey @webianks 
**Details disappear** after a few seconds in Movie Details Activity  .
- When Scrolled Up and Down
- When returned from Full Screen Activity 
- It takes Around few seconds to disappear

**Comment by webianks** [comment]
I will check all these issues. You list down all the issues and fixes needed here in comment.

**Comment by webianks** [comment]
Or make all separate issues

**Comment by salRoid** [comment]
Cool

**Comment by salRoid** [comment]
//TODO call cast Fragment from loader finish
            //TODO Destroy Loader
            //TODO Fragment aur Loader ki aapas mein nai banti , to bnani padegi
            //TODO I think is the solution of glitch
check out these TODO in movie details Activity

**Comment by webianks** [comment]
# Okay Okay !!

**Comment by salRoid** [comment]
ok

**Comment by salRoid** [comment]
Okay let's test it before we close it

**Comment by webianks** [comment]
Turns out its a bug in the loaders api.

Hacked this with the null check.[temporarily]
Also it should be in onResume to reload it activity is paused.
