### ISSUE TITLE
ProgressBar in CastFragment.java

### ISSUE THREAD

**Issue by mik-dass** [salRoid/Filmy#55]
I think there should be progressbar in CastFragement.java . During loading some users might think that the app is not loading the cast members. This will increase the overall usability.

**Comment by webianks** [comment]
Thanks @mik-dass for pointing this.

**Comment by salRoid** [comment]
Thanks for your suggestion @mik-dass , we will implement this in next module.

**Comment by mik-dass** [comment]
Happy to help... :+1:
