### ISSUE TITLE
ButterKnife is not a dependency injection library

### ISSUE THREAD

**Issue by ppamorim** [salRoid/Filmy#61]
It's a annotation processor for binding views.

**Comment by webianks** [comment]
'So what is this [ https://dzone.com/articles/dependency-injection-roboguice](url) ?

**Comment by ppamorim** [comment]
Cool and fresh: http://stackoverflow.com/questions/20821148/difference-between-dagger-and-butterknife-android

**Comment by ppamorim** [comment]
TL;DR

If you use Dagger to try and inject views you're going to have a very bad time :) Try to think of Butter Knife as a means of binding views rather than injection. I only called it injection because all the RoboGuice converts were complaining about lack of "view injection" with Dagger. It's not really injection at all. Like the answer mentions, it's just a way to reduce boilerplate. Under the hood it's just calling findViewById like you would!

**Comment by salRoid** [comment]
Thanks for your explanation @ppamorim ,changes have been made .

**Comment by salRoid** [comment]
Thanks for your explanation @ppamorim ,changes have been made .
